### PR TITLE
Update ArborX dependency

### PR DESCRIPTION
**Pull request by streeve**
Use local CMake variable for ArborX dependency. This fixed some local build issues.

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
I am not sure what issue you are trying to resolve.
I think using `Cabana_ENABLE_ARBORX` directly was the appropriate to do.

**Comment by junghans** [comment]
Does it make sense to build CabanaMD without ArborX, when Cabana has ArborX?

**Comment by streeve** [comment]
> I am not sure what issue you are trying to resolve.

I'm having local build issues where it doesn't pull in `Cabana_ENABLE_ARBORX`

> Does it make sense to build CabanaMD without ArborX, when Cabana has ArborX?

Maybe to avoid compilation time

**Comment by streeve** [comment]
Closing - updated include order will fix

**Pull request closed without merging**
